### ISSUE TITLE
`messageAgeMax` not documented

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1138]
https://github.com/MetPX/sarracenia/blob/6ef61f6ba0358ba5ef3c994b4da1c8219efe95fc/sarracenia/flow/__init__.py#L988-L992

It's not documented in the sr3 options document.

**Comment by petersilva** [comment]
It's not implemented either... there is the test, but there is nothing to set it.
```
SSC-5CD2310S60% find . -name '*.py' | xargs grep messageAgeMax
./flow/__init__.py:            if self.o.messageAgeMax != 0 and lag > self.o.messageAgeMax:
./config.py:        self.messageAgeMax = 0
SSC-5CD2310S60%
```

weird... should we hook it up with *expire* make it a synonym? or is it different?

**Comment by petersilva** [comment]
there is also message_ttl. hmm...

**Comment by reidsunderland** [comment]
Setting it in the config does set the value though... 

```
# in config file:
messageAgeMax 1d
# from sr3 show:
 'messageAgeMax': 86400.0,
```

**Comment by petersilva** [comment]
That should not work... if it isn't declared anywhere, it should be a  string... how it knows that it is a duration... is surprising...

**Comment by reidsunderland** [comment]
yeah, I'm surprised too :D

**Comment by petersilva** [comment]
https://github.com/MetPX/sarracenia/blob/development/sarracenia/config.py#L1723-L1729

Since it is initialized to zero (integer value) it is assumed to be a duration... lucky? I guess is one way to describe it.

**Comment by petersilva** [comment]
looking at ttl's etc...
* expire   ...  when an idle queue dies.
* message_ttl ... age of a message to be dropped by broker.
* nodupe_ttl ... age of a message to be removed from cache
* retry_ttl ... as above, but retry_cache.
* messageAgeMax (undocumented) ... normal message processing ... discard too old.
* fileAgeMax ... normal message processing, discard too old.


so... message_ttl covers the same idea, but is for posting.  Applies to both mqtt and amqp...

suggestions:

* queueExpire ... queueIdleMax ... when a queue will be dropped if not in use... as synonyms for expire.
* messageAgeMax is documented as oldest message to process.
* post_messageAgeMax is synonym for message_ttl.

debate ... just use ttl, since both mqtt and amqp use that... in place of messageAgeMax ...  message_ttl, post_message_ttl, queue_ttl, 

debate ... just use expire... since messsage_expire, post_message_expire, queue_expire

use messageAgeMax where it has nothing to do with protocol (actual words used in protocol involve ttl.)

so then retry_messageAgeMax, nodupe_messageAgeMax as synonyms ... 

consensus seems to be around **messageAgeMax** as the *standard* term... and adjust synonyms etc... to match.

**Comment by petersilva** [comment]
#1147 just merged.
