### ISSUE TITLE
Ack Redesign - primarily applies to AMQP?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1155]
Related to #953, #339, #1278.

We've realized that the current implementation of ack in moth/AMQP is wrong. 

https://github.com/MetPX/sarracenia/blob/301519e6edf0c4288f8fc2fbe25208a7d50d12e3/sarracenia/moth/amqp.py#L573-L610

If acking fails, we currently teardown the AMQP connection and reconnect, which invalidates all other messages waiting to be acked because delivery tags (ack_id) are per channel scoped (and per connection, because channels are per connection). 

We need to refactor this, so we don't close the connection and reconnect. If an ack fails, I think we should just throw away the message on our side and let the broker redeliver it. Reconnecting can happen somewhere else (get_message?) if it's really necessary.

By looping in the ack method, we also block other parts of the code, including blocking potential message consumption from another broker (#339). There are other parts of the AMQP moth class that might be blocking as well (and some behaviour can be changed to non-blocking using the message_strategy stubborn option). 

This has kind of been discussed a bit on other issues, but I think it's a big enough topic to have its own issue.

**Comment by reidsunderland** [comment]
Some ideas that @petersilva and I talked about yesterday not quite specifically related to ack error handling, but more related to how we deal with acking (or not acking) messages after we've re-connected to a broker.

We need to be careful to ensure we don't attempt to ack a message that was received on a different connection/channel. If we do that, we'll cause a "PRECONDITION_FAILED - unknown delivery tag" error and the broker will shut down the connection. 

Options: 

1) When the connection is lost, implement something that lets the moth classes notify the flow algorithm that the connection was lost and the currently un-acked messages should be discarded (i.e. don't even try to call the moth class' ack method for those messages).
2) Assign a UUID or other identifier to each AMQP connection and store that ID + the channel number in each message when we receive it. Then the moth class' ack method can look at the ID and channel number in the message and refuse to ack any messages that don't match the currently active connection and channel. (I think this might be easier to implement?)
3) other?

**Comment by petersilva** [comment]
I think we can just have the "ack_id" in amqp combine the hash and the connection relative thing... don't need another field, just have the amqp put the connection stamp in the ack_id.

**Comment by petersilva** [comment]
by combining them, there is no change outside AMQP at all.  when the connection is established, have a state-variable with connection hash, include that in each message, and in ack, parse the ack_id in two, and ignore if they don't match.

**Comment by reidsunderland** [comment]
yeah that sounds good to me.

(I'm pretty sure) ack_id is currently a number, do you have any preference for what I change it to?

Maybe a dictionary? 

```
{
    delivery_tag: --> number, what we currently put in ack_id,
    connection_id: --> the new connection UUID,
    channel_id: --> the channel ID ,
}
```

or I could use a string, but I like that seems uglier

**Comment by petersilva** [comment]
dictionary sounds good.  in the multi-broker case, will add broker to it.

**Comment by petersilva** [comment]
why ack... discard ack_id vs. whole message:

* acking after successful transfer provides back pressure to broker... so we don't download messages for data we cannot download.

* if the only remedy for a bad ack is to tear down the connection, and in AMQP we know the acks are scoped within the connection, then we can never recover them afterward... it means *ack* in sr3/AMQP must always *succeed* (cannot be retried) so once we try once, we should delete m['ack_id'] (to signify no future ack possible or expected.)

Should we discard the message: ? 
* we (one instance or another) will get another copy of the message eventually (because it wasn't acked.) so this results in redundant message and data transfer, but...
* We have the data now... suppressing it just delays the transfer (in a real-time transfer system... kind of subverting the goal.)  
* when we get to the point of acking... we already have the data and are ready to forward.

Ack id's on AMQP are per connection, and start at 1 (1st message on a connection.) if you nack or don't ack, then the broker will re-assign the message to the ready queue?  It doesn't seem to resend with the same ack.... **to be clarified.**

**Comment by reidsunderland** [comment]
I pushed the changes I have to issue1155_ack_refactor, the key changes are summarized in the commit message (and pasted here)

- moth's ack now returns a boolean and passes off handling of ack failures to the caller (message.gather's ack method)
- message.gather's ack now deletes the ack_id from messages instead of the moth classes
- AMQP: refuses to attempt to ack a message if it was received on a different channel, connection or broker (preventing unecessary connection tear down and re-establish)
- AMQP: when ack is attempted and fails because the connection to the broker is broken, don't loop and retry. After re-connecting, acking that message would always fail, prevents a potential infinite loop

f4ca34a
