### ISSUE TITLE
Add stat call to transfer protocols, and logic to avoid useless retries when source changes.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1157]
Based on inconsistencies between messages and upstream servers caused by changes in the products and lag on the consumer side, it is relatively common to download a file and the result to have a different size than what is expected based on the message. Current logic tries to download again until size matches (unless AcceptSizeWrong is set), and failing a few attempts puts the message on the retry queue for a subsequent attempt (after 5 minutes, typically.)

It might be better if, when it downloads the file, rather than blindly trying the download again, it would check with the server if everybody agrees on the size. Essentially, it should do a stat() call... the implementation of stat would vary per transfer protocol.

* get_http_headers() could be used to implement stat() for https.
* ls could do it for SFTP and perhaps FTP.
* actual os.stat() would work for file protocol.

So you do a stat() of the upstream resource. if the stat succeeds and if its size does not match the message. then retrying the download will never succeed. so should give up, rather than retry.

observations:

* if we give up, and the subscriber is always far behind the source, then the subscriber will never get any data at all... kind of a resource starvation thing.

* if you try to download something, then put it on the retry queue, then get a new message... that works... but a minutes later you pull the same resource out of the retry queue... it will fail again (because the newer version is already downloaded.) ...  logically... we should be updating the retry queue with subsequent successes.

**Comment by petersilva** [comment]
We have one product stream (citypage_weather) where the files are re-written constantly, like three or four times within 30 seconds... and then are static for an hour or so... but then get re-written multiple times in a short interval.

So this creates a stream where you have four messages of updates for the same "file" and if the consumers are more than a 30 seconds behind the source, then by the time they try to download, they will get a newer file than what is expected, and then... how to deal with that.

**Comment by petersilva** [comment]
It would appear that the most robust answer is "Don't do that" ... put a robust date stamp in the name the file to differentiate it and have four products issued in a minute if you must, but don't re-publish the same product (with the same name) too quickly.

**Comment by petersilva** [comment]
Here's a sample message:
```

2024-08-11 00:00:47,978 [INFO] sarracenia.flow download upstream resource is newer, so message https://hpfx.collab.science.gc.ca //20240811/WXO-DD/citypage_weather/xml/NB/s0000653_e.xml is obsolete. Discarding.

```
if it's not newer, but the size does not match:

```

2024-08-11 00:00:47,978 [INFO] sarracenia.flow download matches upstream source, https://hpfx.collab.science.gc.ca //20240811/WXO-DD/citypage_weather/xml/NB/s0000653_e.xml  but not the message received. Discarding.

```

In both cases it retrying the download will change nothing, because it will just be incorrect again,
so the messages are discarded.

**Comment by petersilva** [comment]
with this modification, the retry_queue for a citypage flow is empty:
```

fractal% sr3 status
status: 
Component/Config        Processes   Connection        Lag                              Rates                                        
                        State   Run Retry  msg data   Que   LagMax   LagAvg  Last  %rej     pubsub   messages     RxData     TxData 
                        -----   --- -----  --- ----   ---   ------   ------  ----  ----     ------   --------     ------     ------ 
subscribe/hpfx_citypage run     1/1     0 100%   0%     0    9.57s    7.67s 56.0s 25.0%      7 B/s      0 m/s  1.7 KiB/s      0 B/s 
      Total Running Configs:   1 ( Processes: 1 missing: 0 stray: 0 )
                     Memory: uss:45.1 MiB rss:60.0 MiB vms:95.7 MiB 
                   CPU Time: User:8.68s System:2.01s 
	   Pub/Sub Received: 0 m/s (7 B/s), Sent:  0 m/s (0 B/s) Queued: 0 Retry: 0, Mean lag: 7.67s
	      Data Received: 0 f/s (1.7 KiB/s), Sent: 0 f/s (0 B/s) 
fractal% 

```

**Comment by petersilva** [comment]
@reidsunderland given the misery with *requests* dependency, perhaps take the time to re-write using the more built-in urllib.request (note the lack of *s* ) 
* now https/stat() needs a complete re-write
* the stat call also had the limitation that auth was not supported, perhaps the re-write will fix that (stretch goal, not mandatory.)

**Comment by petersilva** [comment]
We have the internal citypage use case for this, but also downloads from airnow have the same problem:

```
2024-08-27 18:08:33,221 [WARNING] sarracenia.transfer read_writelocal util/writelocal mismatched file length writing HourlyData_2024082701.dat. Message said to expect 733370 bytes.  Got 762695 bytes.
2024-08-27 18:08:33,221 [ERROR] sarracenia.flow download download more 762695 than expected 733370 bytes for HourlyData_2024082701.dat
2024-08-27 18:08:33,222 [INFO] sarracenia.flow do_download attempt 1 failed to download https://s3-us-west-1.amazonaws.com//files.airnowtech.org/airnow/today/HourlyData_2024082701.dat to /apps/sarra/public_data/20240827/AIRNOW/AIRNOWTECH/03/HourlyData_2024082701.dat
2024-08-27 18:08:33,222 [WARNING] sarracenia.flow do_download downloading again, attempt 2
```

**Comment by petersilva** [comment]
also marine_weather.

**Comment by reidsunderland** [comment]
I confirmed that the urllib stat code works for password protected files. 

Just need to test redirection now.

**Comment by reidsunderland** [comment]
I confirmed that a HEAD request that receives a 302 response will follow the redirection and do a GET request for the new URL. More code is needed... :(

**Comment by reidsunderland** [comment]
I have it (redirection using HEAD requests each step along the way, instead of an initial head and then switching to get)  working, but I've made a mess of the existing code that I need to sort through. 

---

I think I've found bugs in the existing HTTPS transfer class, but I'm very confused because it seems like one of them would have prevented HTTP with authentication from working. But it works fine. 

We handle HTTP authentication by creating an OpenerDirector instance called `opener` in our code. Then we call `opener.open(url)` which should do a GET request. But we do nothing with the result that gets returned from that call. We also call `install_opener(opener)` which installs the opener globally and it _should_ apply to all future requests we make. 

https://github.com/MetPX/sarracenia/blob/f7563bc70c0805f18768298df5e6bef0e64a7856/sarracenia/transfer/https.py#L307-L314

This code pretty much comes right from [this example](https://docs.python.org/3/howto/urllib2.html#id5), but I think the example is possibly showing two different ways you can use the opener. You can either interact with it directly by calling `opener.open(...)` _or_ you can install it globally for all future things to use. But it's not clear.

Later, we call urlopen and pass in a context. The result of urlopen is what we actually use for data transfer. So bug 1. is that I think we might be making GET requests to the server twice (once with the opener.open call and once with urlopen).

But, when we call urlopen **and** pass a context, it ignores the opener that gets installed previously.

This is the Python code for urllib that shows how it deals with context. When context is passed in, it creates a new opener and uses that, instead of the global `_opener` that is set by `install_opener`.
https://github.com/python/cpython/blob/6e6855950a1891713369a6cdc84670c38d9388f0/Lib/urllib/request.py#L208-L215

Somehow it works fine anyways.  I did a test and monitored the apache logs on HPFX. I do see two get requests per file. One returns 401 Unauthorized and the next returns 200. 

I'm still confused about why this works, I'm guessing it's because the read method of the urllib.response object uses the globally installed `_opener` instead of the opener used by urlopen.

---

I don't think it's too hard to clean up and fix it, but existing, working code will have to be changed. It's probably a good thing to fix this weirdness, but we'll have to test thoroughly to ensure nothing breaks.

**Comment by petersilva** [comment]
fascinating.

**Comment by reidsunderland** [comment]
A useful note I found in the documentation this morning:

> urllib.request.install_opener(opener)
> Install an [OpenerDirector](https://docs.python.org/3.6/library/urllib.request.html#urllib.request.OpenerDirector) instance as the default global opener. Installing an opener is only necessary if you want urlopen to use that opener; otherwise, simply call [OpenerDirector.open()](https://docs.python.org/3.6/library/urllib.request.html#urllib.request.OpenerDirector.open) instead of [urlopen()](https://docs.python.org/3.6/library/urllib.request.html#urllib.request.urlopen). The code does not check for a real [OpenerDirector](https://docs.python.org/3.6/library/urllib.request.html#urllib.request.OpenerDirector), and any class with the appropriate interface will work.

https://docs.python.org/3.6/library/urllib.request.html#urllib.request.install_opener


And this talks about how when ca... arguments are passed to urlopen, it ignores the globally installed opener. The same is true when a context is passed in, which is what we were doing. 
https://bugs.python.org/issue18543 (https://github.com/python/cpython/issues/62743)

**Comment by petersilva** [comment]
fwiw... I've never looked at any of this stuff.  This is inherited from v2 with just the code being re-factored in terms of class hierarchies.  Someone reviewing it in detail is a very good thing.
