### ISSUE TITLE
v3 sarra not posting the source in messages

### ISSUE THREAD

**Issue by robjarawan** [MetPX/sarracenia#1246]
sr3 `get_upperair_depot.conf` is created to replace the v2 `get_upperair_pxpaz.conf` file, i asked the client to upload the files to depot but the v2 converter is not grabbing them: `cvt_bulletin_filename_from_content.conf`. Reid believes it is not posting the source in the messages - he thinks the problem lies here: 

https://github.com/MetPX/sarracenia/blob/dbb66233bc94707b957f9a751a75b0d374b1ebca/sarracenia/__init__.py#L551-L570

the very last line, source gets added to deleteOnPost, meaning we have a source, but that field will be deleted when we post the message
 
so the downstream cvt sarra receives a message with no source
 
```
sarra_get_upperair_depot_01.log.2024-10-02-2024-10-02 15:09:46,906 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 0.39 ) sftp://user@domain.com /incoming/inukjuak_ue_2024100218_71907.txt

sarra_get_upperair_depot_01.log.2024-10-02:2024-10-02 15:09:54,108 [INFO] sarracenia.flowcb.log after_work downloaded ok: /apps/sarra/public_data/20241002/MSC-INTERNET/UPPERAIR/RAW/15/inukjuak_ue_2024100218_71907.txt

sarra_get_upperair_depot_01.log.2024-10-02-2024-10-02 15:09:54,110 [INFO] sarracenia.flowcb.log after_post posted to exchange: xpublic topic: v02.post.20241002.MSC-INTERNET.UPPERAIR.RAW.15 a file with baseUrl: http://server.domain relPath: 20241002/MSC-INTERNET/UPPERAIR/RAW/15/inukjuak_ue_2024100218_71907.txt```

**Comment by petersilva** [comment]
@reidsunderland  is right... but... source was never intended to be a field that gets forwarded... it is something used within a  flow to identify where the message came from... for the next step in the chain, the "source" is where it got it from ... aka xpublic...

so... this is a case of sr3 doing the right thing, and people implementing flows based on v2 behaviour that wasn't actually intended...  

hmm... Just because it wasn't foreseen doesn't make it wrong.  In general, especially in this case, it makes sense to pass the source around within a pump... just not across pumps... maybe we need a setting:

sourceForward on|off (default off)

**Comment by reidsunderland** [comment]
I think having the option to enable it would be good. The unintended behaviour is quite useful when you have a config (like the converter in Rob's example) that subscribes to multiple trusted sources and puts the output files in `.../${SOURCE}/...`.

The `sourceFromMessage` option is great, because it helps avoid the security risks and potential misconfiguration issues that can happen when using a source from a message. I think posting the source in the message is less risky.

Now that I'm thinking about it, we should also think about how shovels and winnows deal with source. If they get a message with a source field in it, should they pass it along by default?

**Comment by petersilva** [comment]
ok... after thinking a while... I was wondering... whose problem is it if we forward the source field? I'm thinking that if someone doesn't trust the source in a message, then they can set sourceFromExchange... or conversely7 they can set sourceFromMessage if they do.

I'm thinking that here:

https://github.com/MetPX/sarracenia/blob/development/sarracenia/__init__.py#L566-L570

we should add an:
```python

     elif 'source' in msg:  #(but sourceFromMessage is not set.) 
          del msg['source']

```

thoughts::

* nuisance value of having a useless source consuming bytes in messages (if it's not required... and not useful... should normally elided.)
* if you don't trust it, then receiver should discard anyways, so sender is just sending useless bytes.
* on the other hand it IS useful sometimes... and it's really a consumer decision whether to trust it or not, so providing it by default gives the consumer the option to do what makes sense... omitting it takes away the choice.

so... now I'm thinking that...
* we should make sure that source is only produced when sourceFromExchange or sourceFromMessage is set (by the clause mentioned above.)
* always forwarding the source produced... is problably the right idea.
