### ISSUE TITLE
Another run state: disconnected

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1350]
I think an additional run state that indicates connection failures to file transfer services (i.e. not brokers) might be useful, particularly for senders or polls.

If we can't connect to the `sendTo` or `pollUrl`, then show this state. We would know right away that there's a source or destination issue.

Log monitoring would also indicate source/destination problems, but this might be faster to implement.

I'm pretty sure `retry` is the state that would currently be shown in these situations, but an explicit connection error state might be easier to understand.

**Comment by petersilva** [comment]
looking in a metrics file, I found a bunch of relevant ones:


```
 "transferConnected": true, "transferConnectStart": 1734489359.4741669, "transferConnectTime": 26.84036636352539

```
in the sr.py (cli interface) there is:
```
                    if 'transferConnectTime' in metrics:
                            metrics['transferConnectTime'] = metrics['transferConnectTime'] / len(self.states[c][cfg]['instance_metrics'])

                        if 'disconnectTime' in metrics:
                            metrics['disconnectTime'] = metrics['disconnectTime'] / len(self.states[c][cfg]['instance_metrics'])
    .
    .
   .
                       if 'transferConnectTime' in m:
                                m['byteConnectPercent'] = int(100*(m['transferConnectTime'])/time_base)
                            else:
                                m['byteConnectPercent'] = 0

                            if 'disconnectTime' in m:
                                m['connectPercent'] = int(100*(time_base-m['disconnectTime'])/time_base)
                            else:
                                m['connectPercent']= 0

     

```

I think people didn't like have the percentage displayed because in testing it was always 100% so not exciting.
So it's just  a matter of adding a threshold...

say  runStateThreshold_disconnected 50%

if the... metrics show it isn't connected more 50% of the time... then pick flow_status = 'disconnected'.

this is basically a couple of lines of code, more work to test than to implement.

**Comment by petersilva** [comment]
maybe do an or... so disconnect includes broker and transfer in same metric... meaning that one is in disconnected state if we are disconnected from either one.
