### ISSUE TITLE
Flow Test Configurations

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarracenia#157]
Is it an issue that the current flow test only runs properly when `TESTDOCROOT` is set to user home directory? (hardcoded in `flow_setup.sh`)

**Comment by benlapETS** [comment]
It is used to create testdocroot dirs before calling sr_config we should either call sr_config before or grep the setting in default.conf (that would be a bit odd, i think)... It is true that the risk is that it could not be in sync with the config one and it would introduce unecessary problems

**Comment by petersilva** [comment]
um... firstly:   TESTDOCROOT is set to a sub-directory of home, not home itself.
second, it is hard-coded because it needs to be set somewhere.  All other scripts are supposed
to use the value in flow_setup.sh, so that it can be changed once and everyone gets it.
If it doesn't work that way, then it's a bug.

It would be trivial to honour TESTDOCROOT if it is already in the environment.  on the other hand, why the question, what purpose would the added flexibility serve?

**Comment by petersilva** [comment]
question is moot now.
