### ISSUE TITLE
Flow setup sometimes fails on first try

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#168]
This error usually pops up in the log as the issue: `FAILED to start FTP server, is pyftpdlib installed?`

**Comment by petersilva** [comment]
if running on 14.04, there is a note inside flow_setup.sh:  on 14.04 there is no python3-pyftpdlib package available, one needs to install and use python2 version (python-pyftpdlib) so if this is on 14.04 it makes sense.  Does it occur in other circumstances?

**Comment by petersilva** [comment]
fwiw, you have since implemented the CI stuff. and we see the CI stuff fails a little randomly.  I noticed in interactive use, that rarely (for me) the unit test of sr_http fails...  the flow_setup just hangs before printing out anything related to sr_http.   It might be worth trying to isolate. The title of such a bug would be identical to this one, but the reason why is completely different.  do we just keep this bug, or open a new one?

**Comment by petersilva** [comment]
It started failing consistently for me around midnight... by that figured out that it was because the http unit test tries to download a file, and if it is too big it fails.  So I changed the loop there to keep consuming messages until it found a file smaller than 2k.  it might hang less from now on.
commit: 4439bad05f7d4bbe8106ab4c86879efe1b1acdc5

**Comment by benlapETS** [comment]
I have not seen that problem for a while.

**Comment by petersilva** [comment]
I will close this...
