### ISSUE TITLE
Need test sets to run the flow test

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#243]
The flow test is an unpredictable monster when connected live to hpfx feed. We need to implement a module that would take snapshots (records??) of good/problematic sets of msg/files aquired from a flow test which would be reusable when working on/discovering issues. 

We would be able to replay the flow test with those sets and get good insights about fixes and regressions. Basically, this would improve quality control of Sarracenia.

**Comment by benlapETS** [comment]
We could also add a feature to temporize msg flow to avoid receiving a thousand msgs in 1 sec that would bust the flow test on machine with not much resources, if the throughput is not a variable of the test.

**Comment by petersilva** [comment]
feature exists... plugins/post_rate_limit.py

```

post_rate_limit 10
on_post post_rate_limit

```
should limit any posting component to 10 posts per second.

**Comment by petersilva** [comment]
Here is an outline of a way to do this.  A lot of details are likely to be wrong because no-one uses these features very often, but in general,  if someone spent a few hours going through it, it should provide a general method to do case capture and replay.   No new sarracenia code is needed,
just building some configurations, and some mods in the test/ directory scripts.


Case Capture
-------------------

configuration options to do what is needed
```

msg_total_count 1024
on_message msg_total

```
will exit after gathering 1024 messages. 
Starting with a sample like sr_sarra_download_f20,  change the directory it downloads to,
let's call that TD/set_1, and then:
Add:
`
outlet json
`
and sarra will write the posts to a json on standard output (if run in foreground), rather than to a local broker, so redirect it into into, say... TD/set_1/list_of_messages.json. So then all the files downloaded will be under the TD directory, and the posts to announce them will be in the .json file.  If we have files we don't like, we can remove them, and remove the corresponding line in the json file.  Similarly we can add specially crafted files as we like, and easily modify the json to post these as well.

Replay
----------

Then we can add a TD environment variable to the flow_scripts, and have flow_setup accept a test data set name as an argument ( e.g. set_1 ).  need an alternate component to feed the messages
in... an sr_subscribe (or sr_shovel, or sr_cpump) with:
`
restore
save_file TD/set_1/list_of_messages.json
msg_total_count 1024
on_message msg_total

`
The restore option tells it to read all the messages from the json file, and then, since it is 1024 messages, the msg_total plugin will trigger an exit.   Ideally have two shovels (reading the same save_file) replace the t_dd shovels, so that you get two identical feeds into the winnows, and the output should be half of the input... the flow_test should then produce identical output every time it is run with the same input.   

could also do rate_limiting as described previously.

Measurement
-------------------

We would likely want to add to the TD/case_1 directory a list of expected results...
TD/case_1/expected_results.txt which would contain the totals expected for certain numbers.  The flow test would notice if a data set had such results available and compare to what is obtained.

This method describes one way of adapting flow tests to run with fixed data sets, but the fixed data sets could eventually be used to with other tests, the flow_test just provides a first proof of concept.
Other things that could be done later:  performance oriented tests, load measurement tests, etc...
much more characterisation of behaviour is possible once *weather data weather* is eliminated.
Also, the naming of test data sets (case_1 in the example) allows us to build a suite of data sets.

The json files are human editable, so one could, for example, create fuzzing data sets, or data sets with a wide variety of errors, and ensure correct behaviour in those cases.   For this Issue, I think it would be enough to establish an initial canned data set.

**Comment by petersilva** [comment]
for more info, read the sr_subscribe man page, in particular save/restore...
https://github.com/MetPX/sarracenia/blob/master/doc/sr_subscribe.1.rst#shovel-save-restore

**Comment by petersilva** [comment]
This issue is address by having re-factored flow test into a new repository with a variety of tests:
https://github.com/MetPX/sr_insects It contains:

* unit tests
* static flow ... a static set of 1111 files are included in the repository, and they are explicitly posted.  A series of single instance components process them (eliminating issues of multi-instances) and no looping (no retry queue validation.)   Gives a deterministic first test.  (It takes about one or two seconds to post them all.)
* flakey-broker ... rerun the static test above, but slow it down, so that posting occurs over a number of minutes.  While it is running, turn the broker off and on again.  To validate robustness
* dynamic_flow ... the original flow test, which includes multiple instances, and retry function testing.

All of the tests are referenced in sarracenia travis-ci configuration.  and all tests are run with every commit to master.

With this framework in place one can add additional test cases.
