### ISSUE TITLE
part caching problem

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#250]
OK in the last change I did in sr_cache for parts for log archiving  has problems still
I did not have a chance to dig into it  so for now I did an on_message that decides if the parts
needs to be downloaded by checking the filesize against the  End of Part... so part ending
within the filesize is automatically drop.   I dont have the time to check more.  The issue appeared when Daniel L. was archiving a file that was growing very rapidly... cannot say more about it.

**Comment by michelgrenier** [comment]
yes I used the normal place...  which code are you talking about... the on message plugin or the cache ...   the plugin is used by Daniel... I had in mind that he could run it for a while... than we can put it in git hub ...   the cache ... I think it is the branch 207 and it was merged so it is in master now.

The key used with part in master is now   path*partflg,chunksize,current_block
But for the last part ... we should use   path*partflg,remainder,current_block
That is the problem... should I have the time for it,  will do the fix, run flow_test and provide through "normal" place :-)

**Comment by petersilva** [comment]
I guess the *normal place* depends on who is looking... To me, the normal place for all code is github, because all dev done by others commits there first after having gone through the flow test gate.  This stuff is irrelevant to the flow_test for now... I guess you mean you are deploying things somewhere internally...  Can you provide some specifics to be able to identify the changes... the name of the plugin, and/or the commit id's relevant to this discussion, so I can confirm if I have them in a branch I am working with? Thanks.

**Comment by petersilva** [comment]
partitioned transfers (and the implementation from v2) are dropped.  bug report no longer relevant.
