### ISSUE TITLE
chmod_log problem.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#523]
in sr3, when using v2 *chmod_log* option, it is interpreted oddly:
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sarracenia/instance.py", line 227, in <module>
    i.start()
  File "/usr/local/lib/python3.6/site-packages/sarracenia/instance.py", line 180, in start
    os.chmod(logfilename, cfg_preparse.permLog)
TypeError: integer argument expected, got float

```
**work-around:** if you replace it with sr3 native *permLog*, problem is solved.   

It should interpret it correctly though.
Someone needs to go spelunking how to get this properly interpreted by the config parser.

**Comment by MagikEh** [comment]
To try to trigger the bug, just add in `chmod_log ###` (with 777,755,604 or any other 3, 3-bit numbers [0-7])

From [v2 Documentation](https://github.com/MetPX/sarracenia/blob/v2_stable/doc/sr_subscribe.1.rst#logs-and-monitoring) the config option's args are as follow:
![image](https://user-images.githubusercontent.com/6865027/172212517-03ebf4fb-6182-4589-bb6f-3a92bc9baaa6.png)

Personally, I'd start my rabbithole (VSCode debugger breakpoint ;) ) around the [synonyms section of the config.py](https://github.com/MetPX/sarracenia/blob/main/sarracenia/config.py#L517) in order to gain an understanding of how the options are parsed, then put into action!

**Comment by petersilva** [comment]
there is a thing called permOptions in config.py, that do the correct parsing...  permDefault is there... but likely need to add permLog to the initialization.  just adding it to the declaration might be enough.
