### ISSUE TITLE
Tests inside main repo or keep separate sr_insects repo?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#545]
With sr_insects and sarracenia being separate repos, it's a can be tricky coordinate changes that affect both repos.

Things like changes to logging messages in sarracenia require simultaneous changes in sr_insects, and this also makes it hard to go back in time and test older Sarracenia code with the main branch of sr_insects.

We've encountered this scenario with the current setup:

1. Developer makes a change to Sarracenia and sr_insects; these changes depend on each other.
2. Developer creates a PR in each repo.
3. The PR in Sarracenia triggers an Actions run using the *existing main branch of sr_insects,* without the commit(s) waiting to be merged with the sr_insects PR. The Actions run will either fail, because the needed changes to sr_insects aren't present, or possibly produce false positive results, because the changes tested by updated sr_insects code haven't been merged.

Then, either:

1. the sr_insects PR is merged first, potentially breaking tests for other sarracenia branches that run before the sarracenia PR is merged
2. or, the sarracenia PR is merged first, again causing invalid Actions test results like in 3. above, this time for the v03_wip or main branch.

Any bugs introduced to Sarracenia may not be detected in either case above.

---

To fix this, we could merge sr_insects into sarracenia, or include sr_insects as a submodule. 

Merging sr_insects into sarracenia creates some other complications:

- Larger repo size (sr_insects includes test data)
- Separate test code for v2 and v3 

A submodule wouldn't have the two issues above, but would be harder to use for people unfamiliar with submodules.

**Comment by petersilva** [comment]
bad things about being in a single repo:

* v2 and sr3 currently are tested using a single test suite.  The way sr3 was built was to make sure it could pass the same test suite as v2.  with this change, likely the tests would change, so that one would create separate v2 and sr3 suites that look the same, but aren't available to run side-by-side.

today, you can export sarra_py_version=2.21.08   and run the flow tests with v2.  separating the two suites into two repos
(on for each software version) ... I dunno, it is different, might be fine... not sure.

Git bisection... how should it work?
----------------------------------------------

git bisection is a bit more difficult if the tests are changing at the same time as the code. Ideally would like to be able to bisect only the code, keeping the test static, to find out when a failure occurred.

If you are adding a feature to the code, using a Test driven development style (currently an option, not mandatory) one could write the test, and then have the code fail. but older versions of the code won't fail because they don't have the test.

If want to write a new test and then bisect to find where the problem happenned, You would need to make the test outside the test suite... and only incorporate it after you have fixed the problem.

**Comment by petersilva** [comment]
I think unit tests being built-in makes a lot of sense.

**Comment by petersilva** [comment]
sr_insects was originally part of the the same repo, it was separated out because:

* it got quite large, there are many tests to run, and when they start dwarfing the application, and including test data it feels odd.  the number of flow tests is unbounded, will continue to grow, the code will become a smaller and smaller part of the repo.
* the point of tests is to test changes in  the code, while being relatively static.  To confirm that stuff still works after a change is made.   yes, while major features are happenning there is some degree of lock-step, but over the long term, longitudinal testing is the goal.
* git bisection was very cumbersome when the tests in the same repo as the code.

by and large, I think the answer here is: No. don't do that it kills git bisection and that's one of the main purposes of flow tests.
