### ISSUE TITLE
option: --dangerWillRobinson option not documented.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#582]
The dangerWillRobinson argument is used to remind users to think twice before executing potentially dangerous/irreversible activities.

It guards, the "cleanup" action... which can delete exchanges and queues in one command...

**Comment by MagikEh** [comment]
There's a current subtle differnce

```sh
# Stops all running background configs, ignores foreground configs.
sr3 stop

# Stops all running background and foreground configs.
sr3 stop --dangerWillRobinson

# stops all running background and forground instances of that config..
sr3 stop $CONFIG
```

Currently, there's an inconsistency between how sr3 stop handles no specified config (defaults to all) and when one (or more?) config is specified in terms of the background and foreground processes that are culled.

The `--dangerWIllRobinson` option can be specified to get users to signify that they want to stop other foreground processes for the user that runs the command. (ie: user root has 3 daemonized instances running and 1 foreground running in a couple of different terminals)

Brought up because of [PR 578](https://github.com/MetPX/sarracenia/pull/578) Path forward is to make single specified configs only cull background processes, foreground processes /should/ only be culled given the `--dangerWillRobinson` flag. 

PS: Docs should 100% Reference https://www.youtube.com/watch?v=OWwOJlOI1nU

**Comment by petersilva** [comment]
I think stop $CONFIG should behave the same as sr3 stop.  It should ignore the foreground ones unless --dangerWillRobinson is specified.

**Comment by petersilva** [comment]
I think this is done, eh?
