### ISSUE TITLE
Unable to Connect to AMQP Queue - What Are the Queue Names?

### ISSUE THREAD

**Issue by gc-nrcan-michael** [MetPX/sarracenia#609]
In attempt to connect to either of the main AMQP data pump URLs specified on:

[https://eccc-msc.github.io/open-data/msc-datamart/readme_en/](https://eccc-msc.github.io/open-data/msc-datamart/readme_en/)

namely,

dd.weather.gc.ca

and 

hpfx.collab.science.gc.ca

using the guide provided in the documentation here:
[https://metpx.github.io/sarracenia/Tutorials/4_api_moth_sub_demo.html](https://metpx.github.io/sarracenia/Tutorials/4_api_moth_sub_demo.html)

The following error is being returned:
```
2023-01-13 15:48:33,449 [WARNING] sarracenia.moth.amqp getNewMessage failed None: Basic.get: (404) NOT_FOUND - no previously declared queue
2023-01-13 15:48:33,450 [WARNING] sarracenia.moth.amqp getNewMessage lost connection to broker
```

The same error is returned when attempting to connect to the URLs using a custom AMQP implementation using RabbitMQ and NodeJS. Since AMQP is a standard, individuals should be able to connect to these URLs regardless of the implementation, Sarracenia or other.

(as a side note, when the `anonymous:anonymous@` authentication is changed/removed deliberately, it does provide a "Not Authorized 403" error, as expected, in both implementations)

To my understanding, the 404 NOT FOUND problem is that we are not specifying the correct queues to ingest data from.

Assuming this is the source of the issue:
What are the queue names so we can ingest data using our Sarracenia implementation?

Otherwise if this is not the cause of this 404 NOT FOUND error, how can we get our Sarracenia implementation to ingest data from these AMQP data pumps?

**Comment by petersilva** [comment]
Users declare their own queues.  There is a naming convention to be respected. in the example document you cited above, there is some python establish the name to declare in the example. 

You can download the entire example as single python file from here:
https://github.com/MetPX/sarracenia/blob/main/sarracenia/examples/moth_api_consumer.py

I just ran it, and it worked for me, so I'm not sure what the source of your difficulty is.

Are you using a jupyter notebook? You have to run the earlier blocks to initialize things
for the code that actually connects... I'm just guessing here...

You do need to install sarracenia (to get the moth class) in order to run the example (but the early parts of the jupyter notebook do that.)  You are free to use or write something else, but it needs to respect the naming convention, or you will get a permission denied trying to declare the queue.  Since you are using the anonymous user, the convention boils down to:   q_anonymous_Anything_you_want...

Ideally the Anything_you_want part would be something that would help folks know who you are,
so we can let you know if we see problems with your access.  

if you want more details on the queue naming convention, you can look here:
https://metpx.github.io/sarracenia/Explanation/CommandLineGuide.html#queue-queue-name-qn-name

Please keep letting us know how things are going... We don't know unless you tell us.

Thanks.

p.s. Note that if your implementation does not keep up with the publication speed, you will lose data as we have limited ability to queue.  It would be great if you can let us know the queues you are using, and we can provide feedback about whether the queues are building or not.  There isn't an ability for end users to inspect queues with amqp.  We know we have users who are continuously losing data (because we have to purge their queues) but we can't identify who they are... (all we have is an amazon aws ip address.)  We would prefer for clients to have a better experience than that... but we literally cannot identify clients if they don't contact us.

p.p.s. You seem to be a GoC user... we can probably get together on GoC teams... you can find me as peter.silva-AT-REMOVE-ME-ssc-spc.gc.ca

**Comment by gc-nrcan-michael** [comment]
```
options['queue_name'] = 'q_anonymous_' + socket.getfqdn() + '_SomethingHelpfulToYou'

**Comment by gc-nrcan-michael** [comment]
It's the end of day here, need to pack it up, we can resume on Monday.

Thank you for the detailed reply Sir!

**Comment by petersilva** [comment]
um... I'm not sure if there is any question to clarify for this issue.  Please re-open if there is reason.

**Comment by franTarkenton** [comment]
I ran into the same issue... the problem is the docs on this page: https://metpx.github.io/sarracenia/Tutorials/4_api_moth_sub_demo.html 

use the syntax `queue_name` however the options object is expecting the queue name to be defined as `queueName`

Ultimately need to change this line: https://github.com/MetPX/sarracenia/blob/4c7585aa45d641ae1cf7f2b33af2e5c8f357a182/docs/source/Tutorials/4_api_moth_sub_demo.ipynb?short_path=d35d8a5#L72

I'm happy to submit a bugfix PR if that would help get this patched up.  For noobs to sarracenia typos like this can be painful!

**Comment by petersilva** [comment]
a PR would be great... yeah... we changed the source code, but not the jupyter notebooks, which are a bit more involved to change.
