### ISSUE TITLE
cache file not being rotated

### ISSUE THREAD

**Issue by habilinour** [MetPX/sarracenia#73]
The cache file is getting bigger without being rotated causing disk space issue.

**Comment by habilinour** [comment]
The same filename  appears many times in the cache file. The file is added to the cache as soon as the upload starts. If the file is very large  and the poll is running every 5 seconds, it means the file will be added to the cache every 5 seconds as long as the file is being uploaded, this could filling up the cache file for the poll that runs so often if the the files are very large.

grep "201807281130_RADAR_COMPOSITE_1KM_DBZ.tif 1,291574924,1,0,0"  poll/ppp1-radar-csv/recent_files_000.cache |wc
    949    3796  148044

**Comment by petersilva** [comment]
I don´t think this can wait a month.

**Comment by petersilva** [comment]
I looked at the cache algorithm, and the behaviour described is normal... in that when the same file is added, it gets appended to the cache file because it has a new update time.  When the clean interval comes, they should collapse into one entry with the latest time (the last entry in the file.) so when once the file is finally written, it should age out.   Weird thing: all the lines in the cache have the same file size, so it isn't being appended to, it is like something is touching the file... oh, it's a poll, and it is still there, of course... hmm...

**Comment by petersilva** [comment]
the cache algo was made for sr_watch... perhaps adjustment needed for sr_poll.

**Comment by petersilva** [comment]
right now... it looks like everything is running normally.  Noureddine was reporting the recent_file cache for one case had grown to Gbyte scale, which is inconvenient, but what I see is only 10's of Meg, which... ok not ideal, but not a serious issue.  So far, looks like WAD: works as designed.

**Comment by petersilva** [comment]
not urgent, so removed assignment to Jun.  It depends on finding huge recent_file caches to determine if this is a real problem.

**Comment by petersilva** [comment]
sr3 fixes this.
