### ISSUE TITLE
`sr3 start poll/*` does not create exchanges when they are missing

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#808]
During the poll migration of the ddsr nodes, it was noticed that exchanges don't get auto declared when they're not yet created.

It would be nice if sr3 would be capable of declaring exchanges for polls (which are usually the components to declare the exchanges?) when they are missing.

This makes `exchangeDeclare` config option not work as intended.

Steps to recreate problem:

1. Create a basic poll config (with declareExchange to True and with a post_exchange that doesn't exist and a post_broker)
2. Run `sr3 enable $YOURPOLL && sr3 start $YOURPOLL`
3. Do all of this without running `sr3 declare $YOURPOLL`

We see that `getSetup` stalls in incremental backoffs. `putSetup` should likely get called prior, which would properly declare the exchange.

**Comment by petersilva** [comment]
uh... I don't think that is what was happening.... For any component that is posting data, you need a *post_exchange* setting.  If the setting is not explicitly set, then it defaults to *xs_amqpusername*...  (say: *xs_tfeed* )  The publisher is the one who declares they
exchange they intend to post to.

The *exchange* setting is used by all consumers of messages, and it also defaults to the same value ( *xs_tfeed* ) So If the poll had nothing in the configuration file, it would have worked fine, using the user's default for both purposes.

The problem was caused by the configuration having an *exchange* setting, which overrode the default with something else (*xs_tfeed_special* ) , without overriding the *post_exchange* as well.  That created a mismatch.

It is the publisher dutifully declared xs_tfeed, but the subscriber tried to bind to xs_tfeed_special instead... which was never created...

I created #804 to print a warning message for when the analyst has configured such mismatched exchange names.  Maybe that's good enough? not sure.

**Comment by petersilva** [comment]
ok... thinking about it... Are you saying that the *declareExchange* option is mis-named?  It gives the impression that it applies to the *exchange* setting, the same way *declareQueue* applies to the *queue* setting... so it's misleading, and might be better as:  *declarePost_exchange* ?  because that is the only one that ever actually gets declared (convention is that it is always the poster that declares exchanges, so it would always reflect *post_exchange* setting....)

**Comment by andreleblanc11** [comment]
I think `declarePost_exchange` would be better. I think it's better to make clear that there is a difference between `exchange` and `post_exchange`

**Comment by andreleblanc11** [comment]
FYI : I'm working on a fix

**Comment by petersilva** [comment]
Thinking about it... this has nothing to do with polls, per say.  It applies to all components, whenever there is a *loop*, that is the consumer is getting messages from the same exchange that the component is posting to.  Probably the fix needs to move the postSetup to some place ahead of the getSetup for all components... or vice-versa (moving the getsetup later...)

I think this can be done with just changing the order in which the callbacks are loaded... just load the poster callback first,
and it will get called first.

**Comment by andreleblanc11** [comment]
That sounds better than what I had in mind. I'll try that out to see if it works.

**Comment by petersilva** [comment]
do we want poll to make post_exchange and exchange the same automagically?

**Comment by andreleblanc11** [comment]
So the order of the callbacks doesn't change the outcome of the error.

The problem really stems from the order of executions between declaring exchanges and binding queues. What I've setup as a patch is the following in `moth/amqp.py` in the method `getNewMessages` where the `+` indicates the new additions to the code

```
         try:
             if not self.connection:
+                if self.o['exchangeDeclare']:
+                    self.putSetup()
                 self.getSetup()
```

With this, I'm worried about the fact we would be running `exchange_declare` multiple times. The pika documentation says 

> This method creates an exchange if it does not already exist, and if the exchange exists, verifies that it is of the correct and expected class.

https://pika.readthedocs.io/en/stable/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingChannel.exchange_declare

**Comment by andreleblanc11** [comment]
We would also likely need to have `exchangeDeclare` set to False by default

**Comment by petersilva** [comment]
Each component has multiple connections, a consumer connection is created by... flowcb/consume/message.py  , and the poster is created by flowcb/post/message.py...
each connection is unidirectional... and the settings each one gets are different.
iow... the *self* in flowcb/post/message.py is a different *self* from flowcb/gather/message.py.

Each channel should only be initialized in a single direction.

You need to get the poster initialization to happen first,  but consumers are not posters.

**Comment by petersilva** [comment]
* only  posters should declare exchanges, NOT consumers.
* it's not correct for a consumer to declare an exchange.

otoh, declaring an exchange (if it exists) usually does no harm.  I don't understand why you are advocating changing the default for exchangeDeclare.

**Comment by petersilva** [comment]
I just re-read the post about what you did on ops... the problem is not that it isn't declaring, it is that by specifying only post_exchange, you have created a mismatch in the oppposite way than you did on dev.  the problem isn't that the exchange isn't being declared, it's that the consumer is binding to a different exchange than the one being declared.  

The situation today with polls, is: if you are doing distributed duplicate suppression, and you want to specify a post_exchange (overriding the default) then you must ALSO specify exchange.

```
post_broker amqp://$USER@ddsr.cmc.ec.gc.ca/
post_exchange xs_$USER_$OTHER
exchange xs_$USER_$OTHER
```

They need to match.

**Comment by petersilva** [comment]
That's why I'm wondering if we should just have poll make them the same (i.e make exchange always be the same as post_exchange.)

**Comment by petersilva** [comment]
for clarity: The workaround here is to reun  *sr3 declare poll/whatever* before you start the poll the first time to initially create the exchange.  That eliminates the race condition.
