### ISSUE TITLE
Quirk with nodupe_fileAgeMax higher then nodupe_ttl on polls

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#904]
When using nodupe, there is a problem that comes up when one of the nodes gets removed from a cluster.

The nodupe settings were
`nodupe_ttl 25200` -> 7 hours
`nodupe_fileAgeMax 2592000` -> 30 days

Those are default values being set at 
https://github.com/MetPX/sarracenia/blob/d13f5c7f8169fd95298af4550d567f6ef0c3f941/sarracenia/flow/poll.py#L35-L36

The nodupe cache on node with vip is getting updated everytime the directory is polled, so files are not expiring from the cache there. But they're also not being re-posted which is correct for sarra download purposes (we don't want to re-download) but maybe not correct for cache synchronization purposes?
 
Because there's no messages being posted, the other node's nodupe cache is not being refreshed, and the entries are expiring from those caches after 7 hours. 

The likely solution is either:
1. Adjust `nodupe_fileAgeMax` to a value below `nodupe_ttl` in the defaults
2. Adjust `nodupe_ttl` to have a higher value then `nodupe_fileAgeMax` in the defaults

Having `nodupe_fileAgeMax` be slightly lower (6 hours?) then `nodupe_ttl` would be great. There are not a lot of use cases where we would need to keep duplicates for so long.

**Comment by petersilva** [comment]
Quark != Quirk.  Two different things... did you mean Quirk?  A quark would be a small problem indeed...

**Comment by andreleblanc11** [comment]
Yes that's what I meant XD

**Comment by petersilva** [comment]
Another option is to emit warnings that when:

* you have a poll with a vip.
* you have fileAgeMax > nodupe_ttl
* you create an error message saying:  old files will get posted repeatedly because of inconsistency?

Another option is to mention in the documentation that these two are related and should be considered together.

Another option is to get rid of one option... and have the value be calculated from the other.

one option doesn't exclude the others, we may want just one, more than one, or all of them.
I am just generating options... I don't want an opinion without trying to explore the solution space a bit... Are there other things we could do?

**Comment by petersilva** [comment]
Proposing new defaults:

* nodupe_ttl =  8 * 60 * 60
* nodupe_fileAgeMax = 7 * 60 * 60

constraints/considerations:

* the longer the nodupe_ttl, the bigger the duplicate suppression cache.  On high traffic flows, this might be a problem.
* the shorter the nodupe_fileAgeMax, the more files we ignore... if sending old files, this won't be appropriate.

Another thing we could do is emit a warning message:

"warning:  fileAgeMax > ttl, old files will expire from cache and potentially be re-ingested. See issue <link here>"
