### ISSUE TITLE
Queue getting changed in spite of queueName setting.

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#905]
When restarting 3 configs on operations, we noticed that, at random, some configurations had taken up a new queueName that had been defined in its cache.

i.e. the new queue value would look something like this in the cache

    q_$USER_$COMPONENT.$CONFIG.51219975.02233416

instead of 

    q_$USER_$COMPONENT.$CONFIG.$HOSTNAME

When performing an `sr3 show`

    'queueName': 'q_$USER_$COMPONENT.$CONFIG.51219975.02233416',

After restarting, the rogue queue names would get defined and the old correct queue names would be left abandoned.

**Comment by andreleblanc11** [comment]
The only place I can see where the `queueName` would get redefined is in `__guess_queueName`

https://github.com/MetPX/sarracenia/blob/d13f5c7f8169fd95298af4550d567f6ef0c3f941/sarracenia/sr.py#L751-L767

**Comment by andreleblanc11** [comment]
The logs, even with `debug True`, don't seem to show much on what's happening. I'm not sure how to reproduce as it seems to be happening at random.

This seems to be happening commonly amongst lots of configurations.

Some configurations will even have the random integers appended to the suffix with part of the $HOSTNAME still present

i.e.

    q_$SOURCE_$COMPONENT.$CONFIG.58700425.19012547c.ec.gc.ca

**Comment by petersilva** [comment]
that's really not good.

**Comment by andreleblanc11** [comment]
I turned on `debug` mode on one of the affected configs after I restarted them yesterday. 2 queue names have already been changed in less than 24 hours.

Looking at the logs, there isn't anything obvious indicating that the `queueName` has changed or that the cache got tampered with 😢 

I tried looking for `getSetup` calls, seeing if the config got stopped, the old/new queue names.. nothing is showing up

Is there anything else I could try looking for?

**Comment by petersilva** [comment]
without specific configs/examples... it's hard to invetigate this.

**Comment by reidsunderland** [comment]
After more investigation, what seems to be happening is:

1) no qname file is present in the cache
2) a config is started up, it uses the correct queueName from its config file and writes a qname file with the correct name.
3) something happens, changes the contents of the qname file to the wrong queue name
4) the problem sits there waiting until someone restarts the config - then it restarts using the wrong queue name from the qname file and the queue with the correct queue name is left behind on the broker, with nothing consuming from it

We don't know exactly what is causing the qname file to change in step 3. 

@petersilva said that sr.py and config.py have different logic for guessing the queueName.

The timestamp on the qname files seems to change every time `sr3` is run (e.g. sr3 status, sr3 sanity, sr3 dump, sr3 show)

**Comment by reidsunderland** [comment]
I was able to reproduce the problem! I did this:

```bash
./try_to_break_qname_rs.sh & ./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &./try_to_break_qname_rs.sh &
```

try_to_break_qname_rs.sh = 

```bash
sr3 sanity sender/my-config 2> /dev/null > /dev/null &
sr3 dump sender/my-config 2> /dev/null > /dev/null &
sr3 status sender/my-config 2> /dev/null > /dev/null &
```

**Comment by petersilva** [comment]
fwiw. I took the no_mirror test in the sr_insects, added queue_name settings to as many configurations as I could, then left it running overnight, and ran sr3 sanity in a loop every second.  It was fine.

**Comment by reidsunderland** [comment]
This is a cleaner version of the script to reproduce the issue:

```bash
echo 'Current time:'
date
echo
echo 'qname file before:'
cat ~/.cache/sr3/sender/my-config-name/*qname
echo
echo
echo 'Modification time:'
ls -hal ~/.cache/sr3/sender/my-config-name/*qname

for i in {0..15}; do
        sr3 sanity sender/my-config-name 2> /dev/null > /dev/null &
        sr3 dump sender/my-config-name 2> /dev/null > /dev/null &
        sr3 status sender/my-config-name 2> /dev/null > /dev/null &
done


wait


echo
echo
echo
echo 'Current time:'
date
echo
echo 'qname file after:'
cat ~/.cache/sr3/sender/my-config-name/*qname
echo
echo
echo 'Modification time:'
ls -hal ~/.cache/sr3/sender/my-config-name/*qname
```

**Comment by petersilva** [comment]
so @reidsunderland can easily reproduce the problem by running multiple actions overlapping... we see it is a race condition in config.py which strangely re-writes the .qname state file... even for actions like 'status' and dump.   @reidsunderland suggested that this leads to a race condition where sometimes the qname file is empty, and the current code creates a default name for that case.

proposals:

* add a gate not to ever re-write the file when doing a status, or dump ... or really anything other than foreground/start/declare ( 0c4106d7d7334e923f737a3cba2541a40b523a92 )

 (this is actually a little complicated because in "finalize()" we don't necessarily know what action is being done... might have to add logic so that we do...)
* when writing the queueFile, write it to .tmp first, then (atomically) rename to avoid ever having empty file. (refuse to write if the .tmp file exists) or loop. ( d130b9215cac8307f521993e0ecce1ae780b339a )
* add locking (flufl.lock...) to avoid concurrent access to qname file.   (We hate adding a dependency... and it seems like overkill anyways...) NOT DONE.
* add a check for file existence before writing...  ( d130b9215cac8307f521993e0ecce1ae780b339a )
* The only time the qname file should be re-written is in corruption case, so never wriite it if already exists.
   ( d130b9215cac8307f521993e0ecce1ae780b339a )
* probably would be clearer if queue declare/write logic in finalize were indented to explicitly exclude that being done by non-lead instances. ( 0c4106d7d7334e923f737a3cba2541a40b523a92 )

* another proposal is to break the stuff out into a resolve_queuename  thing.... and recurse if failure.  ( acda6bb014f5213f0efc1158f26efba30676e76e )





* should we check v2 as well for this cause?

**Comment by petersilva** [comment]
how to add a test for this in the tests (unit, integ. or flow...)

**Comment by reidsunderland** [comment]
I can't reproduce the problem with the issue905 branch!

**Comment by petersilva** [comment]
looked at v2:
* found substantially the same code in sr_consumer.py/set_queue_name.
* if there is a queue name state file, it unconditionally uses it, regardless of any setting. 
  * if you had no setting previously (was randomly assigned.) 
  * you add a queue_name setting... to a v2 config file.
  * it will just keep using the old name until you do a cleanup.
  * I think that's actually correct.  because otherwise the old queue will never get removed.
* weakness is if it reads blank queue name from file, it will use it (same as v3.)

overall "renumbering" issue seem less likely here because not re-writing if already exists.

**Comment by reidsunderland** [comment]
The timestamp on the qname file also hasn't changed since i installed issue905
