### ISSUE TITLE
When `queueName` comes before `broker`, the `${BROKER_USER}` variable is unset

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#906]
v2 config:

```
vip 1.2.3.4
queue_name q_${BROKER_USER}.${PROGRAM}.${CONFIG}.ddsr-dev

logrotate 3
#loglevel debug
suppress_duplicates 900s
suppress_duplicates_basis name

broker amqps://SOME-SOURCE@ddsr-dev/

exchange xs_SOME-SOURCE_winnow


post_broker amqps://SOME-SOURCE@ddsr-dev/
post_exchange xs_SOME-SOURCE

instances 1
sum a
```

sr3 config produced by the converter:

```
# created by: sr3 convert winnow/rs_testing
vip 1.2.3.4
queueName q_${BROKER_USER}.${PROGRAM}.${CONFIG}.ddsr-dev

logrotate 3
#loglevel debug
nodupe_ttl 900s
nodupe_basis name

broker amqps://SOME-SOURCE@ddsr-dev/

exchange xs_SOME-SOURCE_WINNOW


post_broker amqps://SOME-SOURCE@ddsr-dev/
post_exchange xs_SOME-SOURCE

instances 1
identity arbitrary
```

Result:

```
2024-01-25 21:06:51,004 [ERROR] sarracenia.moth.amqp _queueDeclare AMQP getSetup failed to ddsr-dev with Queue.declare: (403) ACCESS_REFUSED - access to queue 
'q_${BROKER_USER}_WINNOW.rs_testing.ddsr-cmc-dev01' in vhost '/' refused for user 'SOME-SOURCE'
```

I modified the configs a bit to change the users and exchange names, and the log lines to match.

I'm not quite sure how to deal with it, should we just add a critical error and refuse to start? Should the converter move the queueName line below broker?

**Comment by petersilva** [comment]
order of lines in a config file is important and the same lines in different order will have different meaning.  The canonical example being playing with the order of accet/reject lines.

The fact the value is not defined is not a bug, the order things show up in a config file is known to be significant.  just like in many programming languages you can't use values before they are defined.

Yes, you need the broker to be defined in order to have a broker_user....  BROKER_USER is  just considered an environment variable currently we just leave undefined variables alone ...

All this to say that stuff currently is working the way it is designed to, no defect apparent.

what to do to make it more obvious is a good question...

Whether to change how it works is another question...

**Comment by petersilva** [comment]
I have a convention that I always place broker as the first line...

**Comment by reidsunderland** [comment]
I don't think we should change how it works, forcing queueName to come after broker is okay, and likely necessary if we add support for subscribing to multiple brokers (#339) (necessary at least if the broker users are different).
