### ISSUE TITLE
sr3: PRECONDITION_FAILED - unknown delivery tag

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#953]
```
2024-02-07 16:27:36,038 [WARNING] sarracenia.moth.amqp getNewMessage failed q_MSC-SCI-CMC.winnow.winnow-ss5-09.smco501: Basic.ack: (406) PRECONDITION_FAILED - unknown delivery tag 3
2024-02-07 16:27:36,038 [WARNING] sarracenia.moth.amqp getNewMessage lost connection to broker

```

On HPC mirroring use case, versions >= 3.0.47 are seeing this error in one particular mirror. Error goes away when client downgrades, and re-appears on all versions above the threshold.

**Comment by andreleblanc11** [comment]
https://github.com/MetPX/sarracenia/issues/896 also has a delivery tag issue, but its for delivery tag `222`.

**Comment by andreleblanc11** [comment]
Are all messages affected by this when the version is >= 3.0.47?

**Comment by petersilva** [comment]
no... in a configuration running hundreds/second, it takes a minute or so... to fail... so it's some unknown subset.

**Comment by petersilva** [comment]
reproduced on client setup... 

```
2024-03-04 16:57:23,362 [DEBUG] sarracenia.flow run B filtered incoming: 58, ok: 0 (directories: 0), rejected: 0, failed: 0 stop_requested: False have_vip: ['AnyAddressIsFine']
2024-03-04 16:57:23,362 [DEBUG] sarracenia.flow do processing 58 messages worked!
2024-03-04 16:57:23,363 [WARNING] sarracenia.moth.amqp ack failed for tag: 9139: Socket closed
2024-03-04 16:57:23,403 [INFO] sarracenia.moth.amqp _queueDeclare queue declared q_MSC-SCI-CMC.winnow.winnow-ss5-00.pas037 (as: amqps://MSC-SCI-CMC@ddsr.science.gc.ca/), (messages waiting: 810)
2024-03-04 16:57:23,403 [INFO] sarracenia.moth.amqp getSetup binding q_MSC-SCI-CMC.winnow.winnow-ss5-00.pas037 with v03.post.*.# to xs_MSC-SCI-CMC_HALL-5-6-OPS-WINNOW00 (as: amqps://MSC-SCI-CMC@ddsr.scienc

```

There are no retry files present anywhere when this happens.

**Comment by petersilva** [comment]
well this is exciting... I turned on some messaging, and three different instances (that all share the same queue) get a message with the same message-id... I would have thought that the msg-id was shared by all consumers of the same queue, but no it isn't... they refer to completely different files... so msg-id's are connection scope, not queue scope.

OK so narrowing search to within a single instance... find messages like:

```

2024-03-04 17:40:51,584 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 37.82 ) ...   'ack_id':'6725',  referring to 2024030412_WEonG_WE_bc_X_WEonG_SN@6_008.png

```

It seems to get processed normally...
then...
```

2024-03-04 17:40:51,629 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 37.82 )   'ack_id':'6726',  refers to 2024030412_WEonG_WE_bc_X_WEonG_SN@6_008.png

```

so we receive the message with the same id twice...

**Comment by petersilva** [comment]
```

winnow_winnow-ss5-03_01.log:2024-03-04 17:41:02,679 [WARNING] sarracenia.moth.amqp ack failed for tag: 6731: Socket closed
winnow_winnow-ss5-03_01.log:2024-03-04 17:41:05,732 [WARNING] sarracenia.moth.amqp ack failed for tag: 6737: Socket closed
winnow_winnow-ss5-03_01.log:2024-03-04 17:41:08,782 [WARNING] sarracenia.moth.amqp ack failed for tag: 6741: Socket closed
winnow_winnow-ss5-03_01.log:2024-03-04 17:41:11,838 [WARNING] sarracenia.moth.amqp ack failed for tag: 6756: Socket closed
winnow_winnow-ss5-03_01.log:2024-03-04 17:41:14,893 [WARNING] sarracenia.moth.amqp ack failed for tag: 6764: Socket closed
winnow_winnow-ss5-03_01.log:2024-03-04 17:41:18,093 [WARNING] sarracenia.moth.amqp ack failed for tag: 6780: connection already closed
winnow_winnow-ss5-04_01.log:2024-03-04 17:41:02,058 [WARNING] sarracenia.moth.amqp ack failed for tag: 6998: Socket closed
winnow_winnow-ss5-04_01.log:2024-03-04 17:41:05,312 [WARNING] sarracenia.moth.amqp ack failed for tag: 7002: Socket closed
winnow_winnow-ss5-04_01.log:2024-03-04 17:41:08,372 [WARNING] sarracenia.moth.amqp ack failed for tag: 7018: Socket closed
winnow_winnow-ss5-04_01.log:2024-03-04 17:41:11,431 [WARNING] sarracenia.moth.amqp ack failed for tag: 7034: Socket closed
winnow_winnow-ss5-04_01.log:2024-03-04 17:41:14,485 [WARNING] sarracenia.moth.amqp ack failed for tag: 7050: Socket closed
winnow_winnow-ss5-04_01.log:2024-03-04 17:41:17,685 [WARNING] sarracenia.moth.amqp ack failed for tag: 7057: Socket closed
winnow_winnow-ss5-05_01.log:2024-03-04 17:41:02,809 [WARNING] sarracenia.moth.amqp ack failed for tag: 6807: connection already closed
winnow_winnow-ss5-05_01.log:2024-03-04 17:41:05,866 [WARNING] sarracenia.moth.amqp ack failed for tag: 6815: Socket closed
winnow_winnow-ss5-05_01.log:2024-03-04 17:41:08,921 [WARNING] sarracenia.moth.amqp ack failed for tag: 6832: Socket closed
winnow_winnow-ss5-05_01.log:2024-03-04 17:41:12,123 [WARNING] sarracenia.moth.amqp ack failed for tag: 6838: Socket closed
winnow_winnow-ss5-05_01.log:2024-03-04 17:41:18,377 [WARNING] sarracenia.moth.amqp ack failed for tag: 6850: connection already closed
winnow_winnow-ss5-06_01.log:2024-03-04 17:41:03,839 [WARNING] sarracenia.moth.amqp ack failed for tag: 6606: Socket closed
winnow_winnow-ss5-06_01.log:2024-03-04 17:41:06,889 [WARNING] sarracenia.moth.amqp ack failed for tag: 6608: Socket closed
winnow_winnow-ss5-06_01.log:2024-03-04 17:41:09,940 [WARNING] sarracenia.moth.amqp ack failed for tag: 6620: Socket closed
winnow_winnow-ss5-06_01.log:2024-03-04 17:41:13,141 [WARNING] sarracenia.moth.amqp ack failed for tag: 6628: Socket closed
winnow_winnow-ss5-06_01.log:2024-03-04 17:41:19,406 [WARNING] sarracenia.moth.amqp ack failed for tag: 6639: Socket closed

```

so the socket closes, and when we re-open we try to ack, but the id is gone... because scope is connection?
how the heck does recovery work if the connection goes down?

**Comment by petersilva** [comment]
I tried replacing raise_signal with kill as suggested by @reidsunderland , but no joy... behaviour looks the same.
Yeah, it is consistent that it sends the same message twice to the instance, about 40 seconds apart.

one guess:
* broker decides 40 seconds is too long and sends it again.
* then it receives the ack from the first send, and discards.
* then it receives the ack from the second send and boom!

**Comment by petersilva** [comment]
* All of the failures are reported in the first instance of each configuration (log files *_01.log)
* The first instance is the one that does occasional queue declares to see how big the queue is.

different symptom.  Started turning on debug messages, and see this:
```
2024-03-04 19:23:46,850 [INFO] sarracenia.moth.amqp ack acknowledging 5376
   .
  .
  .
2024-03-04 19:23:46,852 [WARNING] sarracenia.moth.amqp getNewMessage failed q_MSC-SCI-CMC.winnow.winnow-ss5-04.pas037: Basic.ack: (406) PRECONDITION_FAILED - unknown delivery tag 5376
2024-03-04 19:23:46,852 [WARNING] sarracenia.moth.amqp getNewMessage lost connection to broker

```

This is what I expected to see... an acknowledgement "succeeding" (in that the process sent the ack.) but then a subsequent AMQP interaction reporting that the ack was "bad." ...

**Comment by petersilva** [comment]
even weirder:

```

(venv) [pas037@ppp6login-002 log]$ grep  \'ack_id\':\'5376\' winnow_winnow-ss5-04_01.log
2024-03-04 19:22:57,621 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 2428.72 ) {  ... 'ack_id':'5376', ... - 'new_file':'2024030412_007_GEPS@NCEP@RAW_naefs@north@america_I_QPF_thumb@pr@024@mbr017_228.png',
 }

2024-03-04 19:23:46,850 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 30.05 ) { ... 'ack_id':'5376', ... 'new_file':'2024030412_ssmis_qc',  }

```
in the same log, the same id on the same instance... strange.

**Comment by petersilva** [comment]
If I comment out the queue_declare logic that queries the size of the queue periodically, the problem goes away.
No idea why...

**Comment by petersilva** [comment]
included in 3.00.52.

**Comment by reidsunderland** [comment]
I commented on https://github.com/MetPX/sarracenia/issues/896#issuecomment-2129671285, but I guess this is the correct issue for that discussion?

I don't think this problem is fixed correctly. We still get these WARNINGs in the flakey broker test logs.

--- 

Moved my comment here:

I was looking at the logs from the flakey broker tests and found these errors as well. 

```
log/sarra_download_f20_01.log:2024-05-22 20:54:53,287 [WARNING] sarracenia.moth.amqpconsumer getNewMessage failed q_tfeed_sarra.download_f20.03585506.18805594: Basic.ack: (406) PRECONDITION_FAILED - unknown delivery tag 799
```

I think it's because we:
- receive a bunch of messages
- they get stored in the worklist with ack_ids
- the connection to the broker is lost *before* they get ack'ed
- we tear down the connection and channel and start up a new connection/channel
- then we try to ack messages from the worklist on the new channel, using the delivery tags/ack_ids from the old channel and RabbitMQ correctly does not accept the acknowledgements

I think we need to discard the (unacked?) messages in the worklist when we lose connection to the broker?

**Comment by reidsunderland** [comment]
The delivery tags are per-channel scoped 
https://www.rabbitmq.com/docs/confirms#consumer-acks-delivery-tags

**Comment by petersilva** [comment]
so current state is that the queue size reporting was disabled to fix this more severe problem.
so when you start, sr3 shows the size of the queue when it was started, and never updates it.
To fix this, thinking about closing the consumer once per housekeeping interval, to at least
get it updated, once in a while.

Did some experiments, but nothing submitted for PR yet.  Opened #1127

**Comment by reidsunderland** [comment]
I'm still not convinced that the periodic queue declare was the cause of this problem, I think it just made it worse. 

We still get lots of those errors in the flakey broker test even without the queue declare:

```
WARNING Summary:
Warning: ll_sftp_f62        (21 file)  [WARNING] sarracenia.moth.amqp ack failed for tag: 148: [Errno 104] Connection reset by pee
```

I think we have to decide what to do with messages in the worklist when the connection/channel gets broken/closed and re-opened.

- Un-acked messages that are in the worklist but not acknowledged yet will also be un-acked on the RabbitMQ side.
- Once the connection/channel is is closed, RabbitMQ will put the un-acked messages back to ready state.
- Once the connection is re-established, we have the messages in two places (worklist and RabbitMQ queue).
- If we try to ack them from the worklist after re-connecting, the ack will fail because the delivery tags (message ID) are per-channel and we've opened a new channel.

One option is *discarding any un-acked messages on the sr3 side when the connection is lost*. We'd need a mechanism that will allow the moth classes to tell the rest of sr3 that the connection is lost and that the messages should be discarded. Once we re-establish the connection, RabbitMQ will re-deliver the messages. Or they'll get delivered to another node/instance that is still connected.

Another option is adding a field to the messages to track which connection and channel they came from. We'd need some kind of unique identifier for the connection and channel pair, then our AMQP code could check and refuse to ack a message with a connection and channel ID that don't match the currently active connection/channel. This could cause duplicate processing of messages though, because RabbitMQ would try to re-deliver the previously un-acked message on the new connection+channel.

**Comment by petersilva** [comment]
feel free to uncomment the queue declares to reproduce the issue.  I don't understand why it would cause the issue, but it certainly seemed to.  Can re-activate by un-commenting here to test:

https://github.com/MetPX/sarracenia/blob/development/sarracenia/moth/amqp.py#L244-L246

**Comment by reidsunderland** [comment]
I can still reproduce the problem. I also tried getting rid of the management channel and doing everything on one channel, but I still see the problem so that isn't it.

**Comment by reidsunderland** [comment]
I'm not closer to finding/fixing the problem, I just want to document this so that I don't forget it. I'm pretty sure the error recovery in the ack method is wrong. If the ack fails, we close the connection and reconnect, **then try the ack again**. We shouldn't try acking again after reconnecting.

https://github.com/MetPX/sarracenia/blob/1533f85ea8cf2c23a5d93b419db43e74c09e9cfe/sarracenia/moth/amqp.py#L573-L610

**Comment by reidsunderland** [comment]
I could not figure out why getNewMessage was trying to ack messages. It has to be happening within the AMQP library somehow:
I added these logs:

```python
            logger.info('before basic get')
            raw_msg = self.channel.basic_get(self.o['queueName'])
            logger.info('after basic get')
```

And the after basic get never gets logged when the error happens:

```
2024-07-19 20:05:56,335 [INFO] 1387361 sarracenia.moth.amqp getNewMessage before basic get
2024-07-19 20:05:56,336 [WARNING] 1387361 sarracenia.moth.amqp getNewMessage failed q_REID-DEBUG.winnow.winnow-ss5-02_reid_test.reid: Basic.ack: (406) PRECONDITION_FAILED - unknown delivery tag 145
2024-07-19 20:05:56,337 [WARNING] 1387361 sarracenia.moth.amqp getNewMessage lost connection to broker
```

I still don't know what is causing this. But the way we recover from this error is to tear down the connection and reopen it, which then causes even more ack errors.

To do:
- clean up ack method's error recovery. It's not the source of the issue here but it is wrong. I'm not totally sure if it makes sense to close and reconnect when we get an ack failure. The reconnect will trigger more ack failures down the road, assuming there isn't a real connection problem and we only had one message's ack fail. If we do keep the reconnect, we should not loop and try acking again after reconnecting.
- figure out what to do with messages in the worklist that we can't ack (throw them away?)

**Comment by reidsunderland** [comment]
The passive queue declare is definitely causing problems. I want to see if I can reproduce that problem on a different broker version before deciding that we need to permanently remove the passive queue declare.

Whether or not we can keep the passive queue declare, I think we still need to take care of discarding/not-acking messages after reconnecting.

**Comment by reidsunderland** [comment]
The ack_id's start over after the passive queue declare.

```
2024-07-19 20:59:56,940 [INFO] 1398645 sarracenia.moth.amqp ack acked 294
2024-07-19 20:59:57,040 [INFO] 1398645 sarracenia.moth.amqp ack acked 295
2024-07-19 20:59:57,141 [INFO] 1398645 sarracenia.moth.amqp ack acked 296
2024-07-19 20:59:57,241 [INFO] 1398645 sarracenia.moth.amqp ack acked 297
2024-07-19 20:59:57,342 [INFO] 1398645 sarracenia.moth.amqp ack acked 298
2024-07-19 20:59:57,442 [INFO] 1398645 sarracenia.moth.amqp ack acked 299
2024-07-19 20:59:57,542 [INFO] 1398645 sarracenia.moth.amqp ack acked 300
2024-07-19 20:59:57,643 [INFO] 1398645 sarracenia.flowcb.retry after_work 25 messages to process, too busy to retry
2024-07-19 20:59:57,643 [WARNING] 1398645 sarracenia.moth.amqp metricsReport Passive queue declare
2024-07-19 20:59:57,675 [INFO] 1398645 sarracenia.moth.amqp ack acked 1
2024-07-19 20:59:57,776 [INFO] 1398645 sarracenia.moth.amqp ack acked 2
2024-07-19 20:59:57,876 [INFO] 1398645 sarracenia.moth.amqp ack acked 3
2024-07-19 20:59:57,976 [INFO] 1398645 sarracenia.moth.amqp ack acked 4
2024-07-19 20:59:58,077 [INFO] 1398645 sarracenia.moth.amqp ack acked 5
2024-07-19 20:59:58,177 [INFO] 1398645 sarracenia.moth.amqp ack acked 6
2024-07-19 20:59:58,278 [INFO] 1398645 sarracenia.moth.amqp ack acked 7
2024-07-19 20:59:58,378 [INFO] 1398645 sarracenia.moth.amqp ack acked 8
2024-07-19 20:59:58,478 [INFO] 1398645 sarracenia.moth.amqp ack acked 9
2024-07-19 20:59:58,579 [INFO] 1398645 sarracenia.moth.amqp ack acked 10
2024-07-19 20:59:58,679 [INFO] 1398645 sarracenia.moth.amqp ack acked 11
2024-07-19 20:59:58,780 [INFO] 1398645 sarracenia.moth.amqp ack acked 12
2024-07-19 20:59:58,880 [INFO] 1398645 sarracenia.moth.amqp ack acked 13
2024-07-19 20:59:58,981 [INFO] 1398645 sarracenia.moth.amqp ack acked 14
```

**Comment by petersilva** [comment]
one idea:

* the "scope" of acks is really one pass through the gather/filter/work/post loop.  so at the end of each pass, all messages should be acked.
* If we only do the declare during housekeeping intervals, there should be no messages waiting for acknowledgements.

It might be safe for the ack-ids to start over.  We will only get an Queue count every 5 minutes, but better than nothing.

**Comment by petersilva** [comment]
or... could make sure the q declare happens at the end of the loop... same effect but no waiting.
basically, one way or another worklist.incoming is drained at the end of the loop, either because stuff worked, or  because it is put on a retry queue.  so at the very end, doing a queue declare then, might be ok.

**Comment by reidsunderland** [comment]
I think i might have finally found the bug causing this

https://github.com/MetPX/sarracenia/blob/501eb42f36f31a9ae3cd58c203e3bb263509712d/sarracenia/moth/amqp.py#L252-L261

_queueDeclare calls __connect EVERY TIME it runs

We need a check somewhere, either in __connect or _queueDeclare to only connect if we're not already connected

**Comment by reidsunderland** [comment]
yeah, that's it.

**Comment by reidsunderland** [comment]
and that's the reason the ack_id's were starting over when the queue declare happened before. It's so obvious now 😄

**Comment by reidsunderland** [comment]
The PR for this fix also has what I think is the first pass of the flakey broker test on GitHub using AMQP Consumers. I hope that it's not just a coincidence!

Flakey broker passes in the the AMQP consumer run from the PR: https://github.com/MetPX/sarracenia/actions/runs/10325542504?pr=1160

While it was consistently failing before: https://github.com/MetPX/sarracenia/actions/workflows/flow_amqp_consumer.yml
